remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# --- VERY IMPORTANT FOR POSTS TO RENDER ---
baseurl: ""
permalink: /:title/

collections:
  posts:
    output: true

# --- Theme / Style ---
minimal_mistakes_skin: "dark"

sass:
  style: compressed

# --- Plugins allowed by GitHub Pages ---
plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

# --- Site Info ---
title: "Saral Singh Blog"
name: "Saral Singh"
description: "Thoughts and experiences by Saral Singh"
url: "https://blog.saralsingh.space"

author:
  name: "Saral Singh"
  links:
    - label: "Portfolio"
      url: "https://saralsingh.space"
